"""
    TweezerArray

Array of optical tweezers generated by a two-dimensional
acousto-optic deflector (AOD).

A `TweezerArray` represents a rectangular grid of Gaussian beams
addressing an atomic register. The grid is parameterized by AOD
drive frequencies and amplitudes in two orthogonal directions
(“rows” and “columns”), from which individual beam positions and
powers are derived.

# Fields

- `λ::Float64`                – wavelength of each beam (m)
- `w0::Float64`               – 1/e² waist of each beam at focus (m)
- `P_total::Float64`          – total optical power distributed across the array (W)
- `r0::Tuple{Float64,Float64}` – transverse offset of the AOD reference spot (m)
- `row_freqs::Vector{Float64}` – AOD drive frequencies for the row axis
- `col_freqs::Vector{Float64}` – AOD drive frequencies for the column axis
- `row_amplitudes::Vector{Float64}` – relative amplitudes per row
- `col_amplitudes::Vector{Float64}` – relative amplitudes per column
- `dx::Float64`               – position-to-frequency factor along x (e.g. µm/MHz)
- `dy::Float64`               – position-to-frequency factor along y
- `beams::Vector{GaussianBeam}` – flattened list of Gaussian beam objects
"""
struct TweezerArray
    λ::Float64                          # wavelength in m
    w0::Float64                         # beam waist in m
    P_total::Float64                    # total power in Watts
    r0::Tuple{Float64,Float64}          # offset position 
    row_freqs::Vector{Float64}
    col_freqs::Vector{Float64}
    row_amplitudes::Vector{Float64}
    col_amplitudes::Vector{Float64}
    dx::Float64                         # diffraction angle µm/MHz
    dy::Float64
    beams::Vector{GaussianBeam}
end

"""
    TweezerArray(; λ, w0, P_total, row_freqs, col_freqs;
                   dx = 3µm/MHz, dy = 3µm/MHz,
                   r0 = (0.0, 0.0),
                   row_amplitudes = nothing,
                   col_amplitudes = nothing)

Construct a rectangular `TweezerArray` from AOD parameters.

Row and column frequencies `row_freqs` and `col_freqs` define a
Cartesian grid of spots. Optional `row_amplitudes` and
`col_amplitudes` set relative weights along each axis; if omitted,
they default to uniform weights (`ones`). The outer product of
row/column amplitudes is normalized and used to distribute the
total power `P_total` across all beams.

The position of each beam is computed as

- `x = r0[1] + dx * col_freqs[j]`
- `y = r0[2] + dy * row_freqs[i]`
- `z = 0.0`

and a corresponding `GaussianBeam(λ, w0, spot_power; r0=pos)` is
created for each grid point.

The resulting `TweezerArray` behaves like a vector of `GaussianBeam`
objects and can be indexed or iterated over to access individual
spots.
"""
function TweezerArray(;
    λ, 
    w0, 
    P_total,
    row_freqs,
    col_freqs,
    dx = 3µm/MHz,
    dy = 3µm/MHz,
    r0 = (0.0,0.0),
    row_amplitudes = nothing, 
    col_amplitudes = nothing
)

    if row_amplitudes === nothing
        row_amplitudes = ones(length(row_freqs))
    end
    if col_amplitudes === nothing
        col_amplitudes = ones(length(col_freqs))
    end

    nrow, ncol = length(row_freqs), length(col_freqs)
    rel_powers = row_amplitudes * col_amplitudes'
    rel_powers ./= sum(rel_powers)
    spot_powers = rel_powers * P_total

    beams = GaussianBeam[]
    for i in 1:nrow, j in 1:ncol
        pos = [r0[1] + dx * col_freqs[j],
               r0[2] + dy * row_freqs[i],
               0.0]
        push!(beams, GaussianBeam(λ, w0, spot_powers[i, j]; r0=pos))
    end

    return TweezerArray(λ, w0, P_total, r0, row_freqs, col_freqs,
                        row_amplitudes, col_amplitudes, dx, dy, beams)
end

"""
    Base.getindex(t::TweezerArray, i...)

Index into the underlying `beams` vector.

This allows `TweezerArray` to be used like a 1D collection of
`GaussianBeam` objects, e.g. `ta[1]` returns the first beam in the
flattened row–major ordering.
"""
Base.getindex(t::TweezerArray, i::Int) = t.beams[i]

"""
    Base.getindex(t::TweezerArray, i, j)

Index into the underlying `beams` vector.

This allows `TweezerArray` to be used like a 2D collection of
`GaussianBeam` objects, e.g. `ta[1,2]` returns the beam in the first row 
and the second column.

Beam at (row=i, col=j) has linear index (i-1)*nrow + j
"""
Base.getindex(t::TweezerArray, i::Int, j::Int) =
        t.beams[(i - 1) * length(t.col_freqs) + j]


"""
    Base.iterate(t::TweezerArray, state...)

Iterate over the beams in a `TweezerArray`.

Enables idioms such as
```
for beam in ta
# do something with each GaussianBeam
end
```
"""
Base.iterate(t::TweezerArray, state...) = iterate(t.beams, state...)

"""
    Base.length(t::TweezerArray)

Return the number of beams in the array (`length(ta.beams)`),
i.e. `length(row_freqs) * length(col_freqs)`.
"""
Base.length(t::TweezerArray) = length(t.beams)

"""
    copy(tw::TweezerArray) -> TweezerArray

Create a shallow copy of a `TweezerArray`, duplicating the frequency
and amplitude vectors and copying each `GaussianBeam`.

Useful when deriving modified arrays from an existing configuration
without mutating the original.
"""
function copy(tw::TweezerArray)
    TweezerArray(
        tw.λ,
        tw.w0,
        tw.P_total,
        tw.r0,                              # Tuple is immutable; safe to reuse
        copy(tw.row_freqs),                 # new Vector
        copy(tw.col_freqs),                 # new Vector
        copy(tw.row_amplitudes),            # new Vector
        copy(tw.col_amplitudes),            # new Vector
        tw.dx,
        tw.dy,
        [copy(b) for b in tw.beams],        # copy each GaussianBeam
    )
end

"""
    tweezers_in_col(ta::TweezerArray, col_idx::Int) -> Vector{GaussianBeam}
    tweezers_in_col(ta::TweezerArray, col_idxs::AbstractVector{Int}) -> Vector{GaussianBeam}

Return the beams belonging to one or more columns of a `TweezerArray`.

- `tweezers_in_col(ta, j)` returns all beams in column `j`
  (varying row index).
- `tweezers_in_col(ta, col_idxs)` concatenates the beams from each
  requested column.

The beams are returned in row-major order within each column.
"""
function tweezers_in_col(ta::TweezerArray, col_idx::Int)
    nrow = length(ta.row_freqs)
    ncol = length(ta.col_freqs)
    [ta.beams[(i-1)*ncol + col_idx] for i in 1:nrow]
end
# Multiple cols version
function tweezers_in_col(ta::TweezerArray, col_idxs::AbstractVector{Int})
    vcat([tweezers_in_col(ta, idx) for idx in col_idxs]...)
end

"""
    tweezers_in_row(ta::TweezerArray, row_idx::Int) -> Vector{GaussianBeam}
    tweezers_in_row(ta::TweezerArray, row_idxs::AbstractVector{Int}) -> Vector{GaussianBeam}

Return the beams belonging to one or more rows of a `TweezerArray`.

- `tweezers_in_row(ta, i)` returns all beams in row `i`
  (varying column index).
- `tweezers_in_row(ta, row_idxs)` concatenates the beams from each
  requested row.

These helpers are convenient for addressing or visualizing 1D subsets
of a 2D tweezer grid.
"""
function tweezers_in_row(ta::TweezerArray, row_idx::Int)
    ncol = length(ta.col_freqs)
    start_idx = (row_idx-1)*ncol + 1
    ta.beams[start_idx : start_idx + ncol - 1]
end
# Multiple rows version
function tweezers_in_row(ta::TweezerArray, row_idxs::AbstractVector{Int})
    vcat([tweezers_in_row(ta, idx) for idx in row_idxs]...)
end

"""
    getbeams(ta::TweezerArray)

Return a flattened vector of beams comprising the tweezer array
"""
AtomTwin.Dynamiq.getbeams(ta::TweezerArray) = ta.beams
